server:
  port: 8080

spring:
  application:
    name: USER_SERVICE
  datasource:
    username: doadmin

    password: AVNS_od1yv8U6_AM61fgrKz6
    url: jdbc:postgresql://digital-shop-do-user-14548663-0.b.db.ondigitalocean.com:25060/digital-shop-db

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
services:
  notification-url: http://NOTIFICATION-SERVICE/notification
  product-url: http://PRODUCT-SERVICE/product
  payment-url: http://PYMENT-SERVICE/payment
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://165.232.104.233:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F45284839792F423F4528487566B597033778214125442A472D4B6150
  access:
    expiry: 30000000000
