server:
  port: 8080

spring:
  application:
    name: USER_SERVICE
  datasource:
    username: postgres

    password: 0825
    url: jdbc:postgresql://localhost:5432/user_service_db

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
services:
  notification-url: http://NOTIFICATION-SERVICE/notification
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

